# Generated by Django 3.2.7 on 2021-10-06 01:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='Software Engineer')),
                ('first_description', models.TextField()),
                ('second_description', models.TextField(blank=True, default=' ', null=True)),
                ('profile_img', models.ImageField(upload_to='images/profile/')),
                ('resume', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'About me',
                'verbose_name_plural': 'About me',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=20)),
                ('school_location', models.CharField(max_length=20)),
                ('school_name', models.CharField(max_length=50, verbose_name='School Name')),
                ('specialization', models.CharField(blank=True, max_length=30, null=True)),
                ('start_year', models.PositiveIntegerField(default=2021, validators=[django.core.validators.MinValueValidator(2015), django.core.validators.MaxValueValidator(2021)])),
                ('end_year', models.PositiveIntegerField(default=2023, validators=[django.core.validators.MinValueValidator(2016), django.core.validators.MaxValueValidator(2025)])),
                ('percentage', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Education',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=30, verbose_name='Company Name')),
                ('job_profile', models.CharField(max_length=30)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('start_month', models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default='1', max_length=9, verbose_name='Month ')),
                ('end_month', models.CharField(blank=True, choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default='2', max_length=9, null=True, verbose_name='Month ')),
                ('start_year', models.PositiveIntegerField(default=2021, validators=[django.core.validators.MinValueValidator(2016), django.core.validators.MaxValueValidator(2021)], verbose_name='Year ')),
                ('end_year', models.PositiveIntegerField(blank=True, default=2021, null=True, validators=[django.core.validators.MinValueValidator(2016), django.core.validators.MaxValueValidator(2025)], verbose_name='Year ')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=50, verbose_name='Project Name')),
                ('project_description', models.TextField(blank=True, null=True)),
                ('domain', models.CharField(choices=[('Quantum', 'Quantum Computing'), ('BlockChain', 'BlockChain'), ('AI', 'Artificial Intelligence'), ('Big-Data', 'Big Data'), ('ML', 'Machine Learning'), ('Cloud', 'Cloud Computing'), ('Automation', 'Automation'), ('Android', 'Android Development'), ('Web', 'Web Development'), ('IOT', 'IOT'), ('Networking', 'Networking'), ('Security', 'Network Security'), ('Others', 'Others')], default='Automation', max_length=25)),
                ('git_link', models.CharField(default=True, max_length=1000, null=True)),
                ('status', models.CharField(choices=[('0', 'Pending'), ('1', 'Completed')], default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('category', models.CharField(choices=[('Languages', 'Languages'), ('Tools & Techniques', 'Tools & Techniques'), ('Other', 'Other'), ('Familiar-with', 'Familiar With')], default='Other', max_length=25)),
            ],
        ),
    ]
