# Generated by Django 3.2.8 on 2023-07-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='name',
            field=models.TextField(default='Yash Jain'),
        ),
    ]
